// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQZZ_q4hjIDKW0HjUaxrHywSeog-yz6Gc',
    appId: '1:928626262111:web:cf80c05e1112d11a9c1bea',
    messagingSenderId: '928626262111',
    projectId: 'trouvetonpro-9bdcd',
    authDomain: 'trouvetonpro-9bdcd.firebaseapp.com',
    storageBucket: 'trouvetonpro-9bdcd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxInPSQtTwn4PBvm_2-30U4r2GrqCBZqA',
    appId: '1:928626262111:android:2b6f6101df8e2e9a9c1bea',
    messagingSenderId: '928626262111',
    projectId: 'trouvetonpro-9bdcd',
    storageBucket: 'trouvetonpro-9bdcd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3mmGLUm1__zyH63NUWV8_ZmKA-sq95dM',
    appId: '1:928626262111:ios:0913e6310a9797f99c1bea',
    messagingSenderId: '928626262111',
    projectId: 'trouvetonpro-9bdcd',
    storageBucket: 'trouvetonpro-9bdcd.firebasestorage.app',
    iosClientId: '928626262111-3rhc42drkirb9vk5fmeg1s3779qibnrv.apps.googleusercontent.com',
    iosBundleId: 'com.example.trouvetonpro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3mmGLUm1__zyH63NUWV8_ZmKA-sq95dM',
    appId: '1:928626262111:ios:0913e6310a9797f99c1bea',
    messagingSenderId: '928626262111',
    projectId: 'trouvetonpro-9bdcd',
    storageBucket: 'trouvetonpro-9bdcd.firebasestorage.app',
    iosClientId: '928626262111-3rhc42drkirb9vk5fmeg1s3779qibnrv.apps.googleusercontent.com',
    iosBundleId: 'com.example.trouvetonpro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQZZ_q4hjIDKW0HjUaxrHywSeog-yz6Gc',
    appId: '1:928626262111:web:620c31d7baf5b32f9c1bea',
    messagingSenderId: '928626262111',
    projectId: 'trouvetonpro-9bdcd',
    authDomain: 'trouvetonpro-9bdcd.firebaseapp.com',
    storageBucket: 'trouvetonpro-9bdcd.firebasestorage.app',
  );
}
